table InternetUsage
	lineageTag: 2403c7ce-37d4-42af-8ddf-bbe9d96160f5

	measure 'Avg Internet Users' = AVERAGE(InternetUsage[No. of Internet Users])
		lineageTag: dcbf8fdd-dff9-4d1f-97a0-0968564fdaf7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY Internet Growth %' = ```
			
			VAR CurrentYear = [Avg Internet Users]
			VAR PreviousYr = MAX(InternetUsage[Year]) - 1
			VAR PreviousYearInternet = 
			    CALCULATE(
			        [Avg Internet Users],
			        InternetUsage[Year] = PreviousYr
			    )
			RETURN
			    IF(
			        NOT(ISBLANK(PreviousYearInternet)),
			        DIVIDE(CurrentYear - PreviousYearInternet, PreviousYearInternet) * 100,
			        BLANK()
			    )
			```
		lineageTag: 6b0f026b-5721-4283-b7fe-2168959c102e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Internet Rank' =
			
			RANKX(
			    ALLSELECTED(InternetUsage[Country]),
			    [Avg Internet Users],
			    ,
			    DESC,
			    Dense
			)
		formatString: 0
		lineageTag: 29689063-52a7-4d1c-b257-aa7e56a3172c

	column Country
		dataType: string
		lineageTag: 8b9c4cfa-8d1d-4124-a74f-86387f853b9a
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Code
		dataType: string
		lineageTag: 24056302-4f97-452c-83cd-8768df8b1080
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 7284b93f-ce91-454f-a405-09c7da15f957
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Cellular Subscription'
		dataType: double
		lineageTag: e352172a-1603-40d5-8501-db79dacbb24f
		summarizeBy: sum
		sourceColumn: Cellular Subscription

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Internet Users(%)'
		dataType: double
		lineageTag: 7a1e31a1-c309-4653-9a38-8ee33d2484e5
		summarizeBy: sum
		sourceColumn: Internet Users(%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'No. of Internet Users'
		dataType: int64
		formatString: 0
		lineageTag: 55e79b3b-cf93-4c27-8da5-602ca9c70cb0
		summarizeBy: sum
		sourceColumn: No. of Internet Users

		annotation SummarizationSetBy = Automatic

	column 'Broadband Subscription'
		dataType: double
		lineageTag: 4aa409b5-63d3-4f5e-ad3f-a2e1f59797c6
		summarizeBy: sum
		sourceColumn: Broadband Subscription

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Avg Internet Usage % for color' =
			
			SWITCH(
			    TRUE(),
			    [Avg Internet Users] < 50, "Low",
			    [Avg Internet Users] < 100, "Medium",
			    "High"
			)
		lineageTag: ac4108e6-d4c7-4e22-bdfe-60e64f5c5c4b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition InternetUsage = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\roban\projects\SEIS632\Project 2\datasets\Final.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"", Int64.Type}, {"Entity", type text}, {"Code", type text}, {"Year", Int64.Type}, {"Cellular Subscription", type number}, {"Internet Users(%)", type number}, {"No. of Internet Users", Int64.Type}, {"Broadband Subscription", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{Table.ColumnNames(#"Changed Type"){0}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Entity", "Country"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Cellular Subscription] <> 0) and ([Broadband Subscription] <> 0) and ([No. of Internet Users] <> 0) and ([Country] <> "World") and ([Year] <> 1998 and [Year] <> 1999))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

